<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Exercise_1</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <StartupObject>Exercise_2.Session_3.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Session 2\**" />
    <EmbeddedResource Remove="Session 2\**" />
    <None Remove="Session 2\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Session 2\Student.cs" />
  </ItemGroup>

</Project>
